settings:
    route: 0 # 0 local, 1 nersc, 2 kubernetes
    incrementalUpdate: True
    outFileSuffix: .bcif.gz
    numSublistFiles: 1
    outputContentType: True
    outputHash: True
    inputHash: True # only for reading local files with hash rather than remote file downloads
    batchSize: 1
    nfiles: 3 # limit bcif conversions when testing
    sequential: True # for airflow sequential executor
paths:
    listFileBase: /Users/jamessmith/Documents/github/project-bcif/in
    outputPath: /Users/jamessmith/Documents/github/project-bcif/out
    configPath: NA
urls:
    # set local path for local file reads
    pdbRemotePath: http://prereleaseftp-external-east.rcsb.org/pdb/data/structures/divided/mmCIF/
    csmRemotePath: http://computed-models-external-east.rcsb.org/staging/
    ihmRemotePath: http://prereleaseftp-external-east.rcsb.org/pdb_ihm/data/entries
    pdbHoldingsFilePath: http://prereleaseftp-external-east.rcsb.org/pdb/holdings/released_structures_last_modified_dates.json.gz
    csmHoldingsFilePath: http://computed-models-external-east.rcsb.org/staging/holdings/computed-models-holdings-list.json
    ihmHoldingsFilePath: http://prereleaseftp-external-east.rcsb.org/pdb_ihm/holdings/released_structures_last_modified_dates.json.gz
