settings:
    route: 0 # 0 local, 1 nersc, 2 kubernetes
    incremental_update: True
    out_file_suffix: .bcif.gz
    num_sublist_files: 1
    output_content_type: True
    output_hash: True
    input_hash: True
    batch_size: 1
    nfiles: 3
    sequential: True # for airflow sequential executor
paths:
    listFileBase: /Users/jamessmith/airflow/in
    outputPath: /Users/jamessmith/airflow/out
    config_path: /Users/jamessmith/airflow/config/bcifConfig.yml
urls:
    pdbRemotePath: http://prereleaseftp-external-east.rcsb.org/pdb/data/structures/divided/mmCIF/
    csmRemotePath: http://computed-models-external-east.rcsb.org/staging/
    ihmRemotePath: http://prereleaseftp-external-east.rcsb.org/pdb_ihm/data/entries
    pdbHoldingsFilePath: http://prereleaseftp-external-east.rcsb.org/pdb/holdings/released_structures_last_modified_dates.json.gz
    csmHoldingsFilePath: http://computed-models-external-east.rcsb.org/staging/holdings/computed-models-holdings-list.json


